// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbbgmcdejwrmvyqmbtse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiYmdtY2RlandybXZ5cW1idHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzAxNzUsImV4cCI6MjA2NTAwNjE3NX0.6P2WCsp5cWc27QTYVmeKABb346_YnL7CvWAjL7FnyhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);